/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/**/*.{js,ts,jsx,tsx,mdx}'
  ],
  safelist: [
    // Button variants
    'bg-blue-600',
    'hover:bg-blue-700',
    'bg-gray-600',
    'hover:bg-gray-700',
    'bg-red-600',
    'hover:bg-red-700',
    'border-blue-600',
    'text-blue-600',
    'hover:bg-blue-600',
    'hover:text-white',
    'text-gray-700',
    'hover:bg-gray-100',
    'text-white',
    'shadow-lg',
    'hover:shadow-xl',
    'transform',
    'hover:scale-105',
    'active:scale-95',
    'border-2',
    'border-current',
    'border-t-transparent',
    'rounded-full',
    'animate-spin',
    'mr-2',
    'ml-2',
    'w-4',
    'h-4',
    'border-2',
    'px-3',
    'py-1.5',
    'text-sm',
    'px-6',
    'py-3',
    'text-lg',
    'px-4',
    'py-2',
    'text-base',
    'w-full',
    'cursor-not-allowed',
    'opacity-60',
    'transform-none',
    'cursor-pointer',
    'inline-flex',
    'items-center',
    'justify-center',
    'font-medium',
    'rounded-lg',
    'transition-all',
    'duration-200',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-blue-500',
    // Primary colors
    'bg-primary-main',
    'bg-primary-light',
    'bg-primary-dark',
    'text-primary-main',
    'text-primary-light',
    'text-primary-dark',
    'border-primary-main',
    'border-primary-light',
    'border-primary-dark',
    'hover:bg-primary-main',
    'hover:bg-primary-light',
    'hover:bg-primary-dark',
    'hover:text-primary-main',
    'hover:text-primary-light',
    'hover:text-primary-dark',
    // Secondary colors
    'bg-secondary-main',
    'bg-secondary-light',
    'bg-secondary-dark',
    'text-secondary-main',
    'text-secondary-light',
    'text-secondary-dark',
    'border-secondary-main',
    'border-secondary-light',
    'border-secondary-dark',
    'hover:bg-secondary-main',
    'hover:bg-secondary-light',
    'hover:bg-secondary-dark',
    'hover:text-secondary-main',
    'hover:text-secondary-light',
    'hover:text-secondary-dark'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
} 