version: '3.8'

services:
  student-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_APP_URL=http://localhost:3002
    depends_on:
      - api-server
    networks:
      - 3de-network

  api-server:
    image: your-api-server-image
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://username:password@db:5432/3de_db
    depends_on:
      - db
    networks:
      - 3de-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=3de_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - 3de-network

volumes:
  postgres_data:

networks:
  3de-network:
    driver: bridge 